train: e:/images/water_meter/dial/dataset_split/train/images  # train images (relative to 'path') 128 images
val: e:/images/water_meter/dial/dataset_split/val/images  # val images (relative to 'path') 128 images
test: e:/images/water_meter/dial/dataset_split/test/images

# 表示有几个类别
nc: 1

# Classes
names: ['dial']

# 明确指定任务类型为 OBB
#task: obb